name: Build and Publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        packages:
          - "core"
          - "easy-i18n"
          - "extract"
          # Agrega aquí todos los paquetes que necesites construir y publicar

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{secrets.MY_NPM_TOKEN}}
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Run tests
        run: yarn test:dev

      - name: Generate release(changelog) and publish
        env:
          NPM_TOKEN: ${{secrets.MY_NPM_TOKEN}}
        run: yarn release

